#!/usr/bin/env bash

PROJECT="-"
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
LIME_YELLOW=$(tput setaf 190)
YELLOW=$(tput setaf 3)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

# Tjek for Java Gradle-projekt
if test -f "build.gradle" || test -f "settings.gradle"; then
   PROJECT="Gradle"
   ./gradlew clean build
# Tjek for VueJS-projekt
elif test -f "package.json"; then
   if grep -q '"vue"' package.json; then
       PROJECT="VueJS"
       echo ""
       echo "The following commands will be executed.."
       echo " - pnpm cypress:component" #køre komponent test
       echo " - pnpm cypress:e2e" #køre end-2-end test (her skal du huske og køre pnpm run serve først)
       echo " - pnpm lint" #finder lint issues
       echo " - pnpm typecheck" #finder type issues
       echo " - pnpm build" #bygge
       echo ""
       pnpm cypress:component && pnpm cypress:e2e && pnpm lint && pnpm typecheck && pnpm build
   fi
fi

# Tjek om build fejlede
if [ $? -ne 0 ]; then
    echo ""
    echo "=============================================================================="
    echo "${RED} 🖐  Fejl! ${PROJECT} Build mislykkedes. Annullerer commit!"
    echo "${NORMAL}=============================================================================="
    echo ""
    cat ~/my-git-config/files/nah.txt
    exit 1
fi