#!/usr/bin/env bash

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
LIME_YELLOW=$(tput setaf 190)
YELLOW=$(tput setaf 3)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

# Kør Gradle clean build
./gradlew clean build

# Tjek om build fejlede
if [ $? -ne 0 ]; then
    echo ""
    echo "=============================================================================="
    echo "${RED} 🖐  Fejl! Gradle build mislykkedes. Annullerer commit!"
    echo "${NORMAL}=============================================================================="
    echo ""
    cat ~/my-git-config/files/nah.txt
    exit 1
fi